services:
  # React frontend application
  client:
    build:
      context: ./client
    volumes:
      - /code/node_modules # Allow container to manage its own dependencies
      - ./client:/code
    ports:
      - "5173:5173"
    # Enable HMR websocket connections
    command: npm run dev -- --host

  # Django backend application
  server:
    build:
      context: ./server
    volumes:
      - ./server:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  # PostgreSQL database
  db:
    image: postgres
    # Uncomment to persist data across container stops
    # volumes:
    #  - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
